import test from 'node:test';
import assert from 'node:assert/strict';
import { createOAuthProviderRegistry } from '../server/auth/oauth-provider-registry.js';
import { createPlatformRegistry } from '../server/platforms/registry.js';
import { registerInstagramProvider } from '../server/platforms/instagram/index.js';

test('does not register Instagram when app credentials are absent', () => { const oauthRegistry=createOAuthProviderRegistry(); const platformRegistry=createPlatformRegistry(); assert.deepEqual(registerInstagramProvider({env:{},oauthRegistry,platformRegistry}),{configured:false}); assert.equal(oauthRegistry.has('instagram'),false); assert.equal(platformRegistry.has('instagram'),false); });
test('registers OAuth and publishing adapters when configured', () => { const oauthRegistry=createOAuthProviderRegistry(); const platformRegistry=createPlatformRegistry(); const repository={async getAccount(){return{id:'acct1',provider:'instagram',providerAccountId:'ig-1',state:'CONNECTED',accessTokenEncrypted:'ciphertext'};},async listMediaForPost(){return[{type:'image',url:'https://cdn.example/a.jpg'}];}}; const result=registerInstagramProvider({env:{INSTAGRAM_APP_ID:'app',INSTAGRAM_APP_SECRET:'secret'},oauthRegistry,platformRegistry,repository,cipher:{decrypt(){return'plain-token';}},fetchImpl:async()=>new Response('{}',{status:200})}); assert.equal(result.configured,true); assert.equal(typeof oauthRegistry.get('instagram').getAuthorizationUrl,'function'); assert.equal(typeof platformRegistry.get('instagram').publish,'function'); });
test('publishing credential resolver rejects wrong-provider, disconnected or missing accounts', async () => { for(const account of [null,{provider:'facebook',state:'CONNECTED',accessTokenEncrypted:'x'},{provider:'instagram',state:'DISCONNECTED',accessTokenEncrypted:'x'}]){ const oauthRegistry=createOAuthProviderRegistry(); const platformRegistry=createPlatformRegistry(); registerInstagramProvider({env:{INSTAGRAM_APP_ID:'app',INSTAGRAM_APP_SECRET:'secret'},oauthRegistry,platformRegistry,repository:{async getAccount(){return account;},async listMediaForPost(){return[{type:'image',url:'https://cdn.example/a.jpg'}];}},cipher:{decrypt(){return'token';}},fetchImpl:async()=>{throw new Error('provider should not be called');}}); await assert.rejects(()=>platformRegistry.get('instagram').publish({post:{id:'p1',caption:''},publication:{accountId:'acct1'}}),(error)=>error.code==='AUTH_ERROR'&&error.retryable===false); } });
