import test from 'node:test';
import assert from 'node:assert/strict';
import { createInstagramPublishingAdapter } from '../server/platforms/instagram/publish.js';

function fixture({ media=[{type:'image',url:'https://cdn.example/post.jpg'}] }={}) { const calls=[]; const client={ async postGraph(path,options){ calls.push({method:'post',path,options}); return {id:path.endsWith('/media_publish')?'media-900':'container-100'}; }, async getGraph(path,options){ calls.push({method:'get',path,options}); return {id:'container-100',status_code:'IN_PROGRESS',status:'Processing'}; } }; return { calls, client, resolveCredentials:async(accountId)=>({accountId,providerAccountId:'ig-1789',accessToken:'secret-token'}), getMedia:async()=>media }; }

test('rejects publication without bound account before provider or media calls', async () => { let credentialCalls=0,mediaCalls=0; const adapter=createInstagramPublishingAdapter({ client:{async postGraph(){},async getGraph(){}}, resolveCredentials:async()=>{credentialCalls+=1;}, getMedia:async()=>{mediaCalls+=1;return[];} }); await assert.rejects(()=>adapter.publish({post:{id:'p1',caption:'x'},publication:{id:'pub1'}}),(error)=>{assert.equal(error.code,'ACCOUNT_REQUIRED');assert.equal(error.retryable,false);return true;}); assert.equal(credentialCalls,0); assert.equal(mediaCalls,0); });
test('publishes one image using container then media_publish', async () => { const f=fixture(); const adapter=createInstagramPublishingAdapter(f); const result=await adapter.publish({post:{id:'p1',caption:' Hello '},publication:{id:'pub1',accountId:'acct1'}}); assert.deepEqual(result,{status:'PUBLISHED',externalId:'media-900',containerId:'container-100'}); assert.equal(f.calls[0].path,'/ig-1789/media'); assert.deepEqual(f.calls[0].options.body,{image_url:'https://cdn.example/post.jpg',caption:'Hello'}); assert.equal(f.calls[0].options.accessToken,'secret-token'); assert.equal(f.calls[1].path,'/ig-1789/media_publish'); });
test('creates Reel container and returns PROCESSING while provider is not finished', async () => { const f=fixture({media:[{type:'video',url:'https://cdn.example/reel.mp4'}]}); const adapter=createInstagramPublishingAdapter(f); const result=await adapter.publish({post:{id:'p1',caption:'Reel'},publication:{id:'pub1',accountId:'acct1'}}); assert.deepEqual(result,{status:'PROCESSING',externalId:'container-100'}); assert.deepEqual(f.calls[0].options.body,{video_url:'https://cdn.example/reel.mp4',media_type:'REELS',caption:'Reel'}); assert.equal(f.calls[1].method,'get'); });
test('publishes Reel when container is already FINISHED', async () => { const f=fixture({media:[{type:'video',url:'https://cdn.example/reel.mp4'}]}); f.client.getGraph=async(path,options)=>{f.calls.push({method:'get',path,options});return{id:'container-100',status_code:'FINISHED'};}; const result=await createInstagramPublishingAdapter(f).publish({post:{id:'p1',caption:'Reel'},publication:{id:'pub1',accountId:'acct1'}}); assert.equal(result.status,'PUBLISHED'); assert.equal(result.externalId,'media-900'); assert.equal(f.calls[2].path,'/ig-1789/media_publish'); });
test('getStatus publishes FINISHED container and maps ERROR safely', async () => { const f=fixture(); const adapter=createInstagramPublishingAdapter(f); f.client.getGraph=async(path,options)=>{f.calls.push({method:'get',path,options});return{status_code:'FINISHED'};}; assert.deepEqual(await adapter.getStatus({publication:{id:'pub1',accountId:'acct1',externalId:'container-100'}}),{status:'PUBLISHED',externalId:'media-900',containerId:'container-100'}); f.client.getGraph=async()=>({status_code:'ERROR',status:'provider details'}); assert.deepEqual(await adapter.getStatus({publication:{id:'pub1',accountId:'acct1',externalId:'container-100'}}),{status:'FAILED',externalId:'container-100',errorCode:'MEDIA_ERROR'}); });
test('rejects invalid media before provider HTTP calls', async () => { const f=fixture({media:[{type:'image',url:'http://private.example/a.jpg'}]}); const adapter=createInstagramPublishingAdapter(f); await assert.rejects(()=>adapter.publish({post:{id:'p1',caption:''},publication:{accountId:'acct1'}}),(error)=>error.code==='INVALID_MEDIA'); assert.equal(f.calls.length,0); });
