export const JOB_TYPES = Object.freeze({
  SOCIAL_PUBLICATION: 'SOCIAL_PUBLICATION',
  WHATSAPP_CAMPAIGN: 'WHATSAPP_CAMPAIGN',
  STATUS_CHECK: 'STATUS_CHECK',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  RETRY_PUBLICATION: 'RETRY_PUBLICATION'
});
