export const JOB_STATES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  RUNNING: 'RUNNING',
  RETRYING: 'RETRYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

export const TERMINAL_JOB_STATES = new Set([
  JOB_STATES.COMPLETED,
  JOB_STATES.FAILED,
  JOB_STATES.CANCELLED
]);
