export const PUBLICATION_STATES = Object.freeze({
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  QUEUED: 'QUEUED',
  UPLOADING: 'UPLOADING',
  PROCESSING: 'PROCESSING',
  PUBLISHING: 'PUBLISHING',
  PUBLISHED: 'PUBLISHED',
  RETRYING: 'RETRYING',
  RATE_LIMITED: 'RATE_LIMITED',
  AUTH_ERROR: 'AUTH_ERROR',
  MEDIA_ERROR: 'MEDIA_ERROR',
  API_ERROR: 'API_ERROR',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

export const TERMINAL_PUBLICATION_STATES = new Set([
  PUBLICATION_STATES.PUBLISHED,
  PUBLICATION_STATES.FAILED,
  PUBLICATION_STATES.CANCELLED
]);
